language: node_js
node_js:
  - 8
install:
  - npm install
  - npm install semantic-release
branches:
  only:
    - master

deploy:
  - provider: script
    script:
      - npx semantic-release
    on:
      branch: master
